"""empty message

Revision ID: 577845f6bd1e
Revises: 38fc8d1a45be
Create Date: 2022-02-19 10:56:55.914002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '577845f6bd1e'
down_revision = '38fc8d1a45be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_stock', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.drop_index('ix_current_stock_timestamp', table_name='current_stock')
    op.create_index(op.f('ix_current_stock_purchase_date'), 'current_stock', ['purchase_date'], unique=False)
    op.drop_column('current_stock', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_stock', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_current_stock_purchase_date'), table_name='current_stock')
    op.create_index('ix_current_stock_timestamp', 'current_stock', ['timestamp'], unique=False)
    op.drop_column('current_stock', 'purchase_date')
    # ### end Alembic commands ###
